apiVersion: v1
kind: Pod
metadata:
  name: redis-app-pod
  labels:
    app: redis-app
spec:
  containers:
    - name: app
      image: vanhtuan/redis-app
      env:
        - name: PORT
          value: "3000"
        - name: REDIS_HOST
          value: "redis.default.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
      ports:
        - containerPort: 3000