version: "3"
services:
  loadbalancing-haproxy:
    image: haproxy:alpine
    container_name: c-loadbalancing-haproxy
    networks:
      - loadbalancing # name of network
    restart: always
    hostname: loadbalancing-haproxy
    volumes:
      - "$PWD/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    ports:
      - "80:80"
      - "443:443"
networks: # Create a network
  loadbalancing: # Name of network
    driver: bridge # Driver of network
